### ISSUE TITLE
Py exception with random life

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/inmoov#100]
Hello Anthony,
I found a new bug for you, as I'm sure you are lacking of things to do right now.
:)
The bug is, if you do not have all body parts set as True, and call for the command "Random life", you get a Py exception.
Running version MRL 1.0.2340, and set main script as Full instead of Virtual.
But the left hand is not attached so I have set the skeleton left hand config to False.
Running command Random life, gets me a Py exception and random will not work.

**Comment by moz4r** [comment]
Hi ! I will check soon

**Comment by moz4r** [comment]
soon is today, fixed !

**Comment by hairygael** [comment]
Great!
I wish I could test it, but without an InMoov at hand it's difficult.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-08-28 15:29 GMT+02:00 Anthony <notifications@github.com>:
