### ISSUE TITLE
HINDI language pack

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/inmoov#101]
place for inmoov hindi translators
resources : 

https://github.com/MyRobotLab/inmoov/wiki/LANGUAGE-PACK-DOCUMENTATION

http://myrobotlab.org/content/can-we-use-hindi-language-voice-command
http://myrobotlab.org/content/indian-hindi-text-speech
http://myrobotlab.org/service/IndianTts

**Comment by hairygael** [comment]
Nice,
I wonder if Markus is going to use it in India.
