### ISSUE TITLE
wake up

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/inmoov#106]
Hello testing Version MRL 1.0.2483 with InMoov Master.
When InMoov goes to sleep, the microphone cannot listen. It would be nice if you could vocaly tell him "wake up".
If writting in the chatbot tab: wake up, the robot will wake up but the mic is then still deactivated.
So, the wake up function works properly if the PIR detects movement, and then the mic is correctly working.

Could we fix that easily?

**Comment by moz4r** [comment]
easy !

![image](https://user-images.githubusercontent.com/18124594/30127630-40b133c8-9340-11e7-9ea4-8f9d8b745b83.png)

will look at this . useful too if we don't have pir

**Comment by moz4r** [comment]
precision before commit, do you want the microphone always ON while robot sleeping ? ( off course it will awsers only few commands like wake up or shutdown )

**Comment by moz4r** [comment]
it can be a personnal config thing..

**Comment by moz4r** [comment]
ok pushed inside develop , you can just replace ear.py
robot will respond with microphone or program ab manual entry
will push later this mod inside the jar because quota exceeded :)

**Comment by hairygael** [comment]
Tested and worky!! It's really much better!!
Now lets make it still more difficult.
:)
I think as long as we speak to the robot, even if the PIR doesn't detect movement, the robot should not go to sleep, unless we tell him to do so.

**Comment by moz4r** [comment]
pushed
robot will no longer be insolent and will not fall asleep when you speak to him.

**Comment by hairygael** [comment]
Nice!!
I will test that tomorrow.
:)

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-10-02 23:08 GMT+02:00 Anthony <notifications@github.com>:

**Comment by hairygael** [comment]
This is super!
