### ISSUE TITLE
 i01.disableRobotRandom(30)

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/inmoov#111]
Hello Anthony,
How can we disable the random while doing a gesture now?
 i01.disableRobotRandom(30) is not attributed anymore, this was added in some gestures which aren't working anymore.
I thought the function startedGesture() and finishedGesture() was going to do that but I guess I misunderstood something.
:)

**Comment by moz4r** [comment]
Hi Gael ! i01.startedGesture() will do the job ( + finishedGesture() at the end )

what do i01.startedGesture() : 
- stop servo autodisable
- stop random things
- warn if we launch an other gesture
- we can add other things like stop microphone etc ...

**Comment by hairygael** [comment]
Thanks Anthony,
I just tried with version 2552 and it works!
I need to clean up all the gestures that had i01.disableRobotRandom(30)

**Comment by hairygael** [comment]
In InMoov/Life/MoveRandomize.py there is still:
i01.disableRobotRandom(20)
Is that okay?

**Comment by moz4r** [comment]
bien vu ! 
fixed

**Comment by hairygael** [comment]
Great!
Thank you

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-10-02 17:21 GMT+02:00 Anthony <notifications@github.com>:
