### ISSUE TITLE
Jaw doesn't disable

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/inmoov#114]
Hello Anthony,
Version 1.0.2563 with latest inmoov-develop.
Jaw doesn't autoDisable during random life and doesn't move while speaking after Random Life.
Also Jaw velocity stays on 25 after stopTracking, so that must be why it doesn't move while speaking.

Relax gesture doesn't autoDisable, but it doesn't seem related to Random life.

**Comment by moz4r** [comment]
some little problems but you put a finger on a bug well hidden for a long time. ( last servo position sometime bad ). 
fixed. Is it better ?

**Comment by hairygael** [comment]
It seems to be good now for the jaw!

Relax is not okay, removing the i01.startedGesture() solves the autodisable issue but stops the gesture from being complete.

**Comment by moz4r** [comment]
I think it is the same issue related to last events not blocked, we need more magic : 

https://github.com/MyRobotLab/inmoov/issues/116
