### ISSUE TITLE
Error with OpenWeather

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/inmoov#118]
File "C:/Myrobotlab/myrobotlab.1.0.2596/InMoov/services/H_OpenWeatherMap.py", line 43, in isTheSunShiny
    todayforecast=weather[3].decode("utf-8")
AttributeError: 'NoneType' object has no attribute 'decode'

def isTheSunShiny(townParam=town):
  weather=getRawWeather(townParam)
  
  if weather[1]!=1000 and isChatbotActivated:
    todayforecast=weather[3].decode("utf-8")

**Comment by moz4r** [comment]
Hi Gael, fixed ?
( now OpenWeatherMap will warn user about bad api key )
You can get a free one here : http://openweathermap.org/appid

**Comment by hairygael** [comment]
Hello Anthony,
I haven't tested yet, but I will try and let you know!

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-11-03 0:38 GMT+01:00 Anthony <notifications@github.com>:

**Comment by hairygael** [comment]
Hello Anthony,
Yes now it's giving the warning for the API key

Great!
