### ISSUE TITLE
Globalisation

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/inmoov#151]
We want python script minimal as possible, and things that are not daily usual can be hard coded. 
Today inmoov language pack is parsed from python land, goal is to push inside java land. 
The question is what is the best way.

Language pack is used exemple to talk about startup action, or robot critical errors.
( and of course for chatbot, but this part need to stay in python land )

https://github.com/MyRobotLab/inmoov/tree/master/InMoov/system/languagePack

**Comment by moz4r** [comment]
Table of Language Culture Names, Codes, and ISO Values Method : https://msdn.microsoft.com/en-us/library/ee825488(v=cs.20).aspx

**Comment by kwatters** [comment]
I recommend using the 2 letter ISO-639-1 codes...  I don't trust microsoft for "standards"  :)

https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by moz4r** [comment]
ahaha you right... But we need to deal with things like this, other standards source ?
https://github.com/MyRobotLab/myrobotlab/blob/master/src/resource/WebGui/service/js/WebkitSpeechRecognitionGui.js

**Comment by moz4r** [comment]
ohhh discovering Locale class :) seem powerful

**Comment by moz4r** [comment]
seem we need only 1 thing now, it is loadLanguagePack() . Like loagGestures()
