### ISSUE TITLE
Get Inmoov worky inside nixie

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/inmoov#162]
lot of sub tickets concerned

**Comment by moz4r** [comment]
Controller tab in progress..
Goal is to get things worky if we use the gui or diy script.

![image](https://user-images.githubusercontent.com/18124594/42138161-1676b42e-7d79-11e8-8da4-65be19290b29.png)

**Comment by hairygael** [comment]
Nice!!!
Great job to have graphics gui for new users.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2018-07-01 21:57 GMT+02:00 Anthony <notifications@github.com>:

**Comment by moz4r** [comment]
in parallel and pending a stable inmoov2 will check inmoov1 with nixie

**Comment by moz4r** [comment]
will find an other related ticket for i02
i01 seem ok
https://github.com/MyRobotLab/inmoov/issues/172
