### ISSUE TITLE
Gesture creator

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/inmoov#171]
An idea for the new gesture creator version?
If that could work simulteanously with VirtualInMoov or in Real mode...
https://youtu.be/ECWUPJ0oDaQ

**Comment by supertick** [comment]
references - https://github.com/MyRobotLab/myrobotlab/issues/228

**Comment by supertick** [comment]
I think this will need to be done in the myrobotlab repo - so moving all info there ...

**Comment by supertick** [comment]
closing as duplicate - please follow -> https://github.com/MyRobotLab/myrobotlab/issues/228
since the changes will need to be done to that repo

**Comment by hairygael** [comment]
Some functions of the GestureCreator are broken, but I guess that will
require a refactor anyway.
What seems to be broken is the script import and export, which makes the
GestureCreator currently useless.
I see MaVo is still around MRL, that's great news!
Maybe he will have a look into that super service he made.
:)

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2018-07-01 22:35 GMT+02:00 GroG <notifications@github.com>:
