### ISSUE TITLE
Face recognizer ( seem worky ) but get an error :

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/inmoov#179]
21:29:00.171 [AWT-EventQueue-0] ERROR c.m.f.Instantiator [Instantiator.java:21] getNewInstance failed for null org.myrobotlab.swing.opencv.OpenCVFilterPyramidDownGui class java.lang.ClassNotFoundException

**Comment by kwatters** [comment]
This should be a warning, it's because there is no gui for the PyramidDown filter.  All opencv filters that don't have a default gui will throw this exception.
