### ISSUE TITLE
check available languages

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/inmoov#181]
if worky ..

**Comment by supertick** [comment]
I think there is a language index in the AbstractSpeechSynthesis ... is that what your asking about ?

**Comment by moz4r** [comment]
oh, for now it is just to test languages packs ( chatbot sets & vocal errors ) Inside inmoov script, seem there is some that need fixes

**Comment by supertick** [comment]
not sure what needs to be done ... how would I test ?
