### ISSUE TITLE
Re-Package and post "New" version of InMoov scripts

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/inmoov#182]
currently - errors are occurring like the following
  File "C:/mrl.test/nixie.2/InMoov/services/7_Inmoov.py", line 13, in <module>
    varduinoright.serial.usedByInmoov=True
AttributeError: 'org.myrobotlab.service.Serial' object has no attribute 'usedByInmoov'

It looks like these problems have been cleared up on the develop branch - but it also means we need a new package with a incremented version posted on mrl's repo - http://repo.myrobotlab.org/artifactory/webapp/

**Comment by moz4r** [comment]
It should launch now. lot of things to test :)

**Comment by supertick** [comment]
1.1.3 now bundled and posted to artifactory
