### ISSUE TITLE
Arm Commands

### ISSUE THREAD

**Issue by mayaway** [MyRobotLab/inmoov#2]
I have my ScriptType=Full
"arms front" seemed to work once
"da vinci" hasn't worked at all, even after renaming the voice name "arms gesture" since voice recognition kept failing at producing "da" space "vinci"
I can't find where either command is even defined! 
Can I add my own ear.commands and defs?

Thank you!

**Comment by hairygael** [comment]
Hello mayaway,
I see that you are trying to use "Merge them All",  what we have just
started only two weeks ago with MRL and Anthony (moz4r)
At this state, it is really only a work in progress. Many things DO NOT
WORK YET.
When it will be ready we will make an official annoucement.
But if you feel confident you are welcome to work with us.

If not:
I recommend if you want to run a full InMoov to follow this tutorial and
install the Kraken version:
http://inmoov.fr/how-to-start-myrobotlab/
The zip contains everything you need to get your InMoov working, the script
available is here:
https://github.com/MyRobotLab/pyrobotlab/blob/master/home/hairygael/InMoov3.Deep.AB.V7.py

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-01-05 11:57 GMT+01:00 mayaway <notifications@github.com>:
