### ISSUE TITLE
Jaw won't detach after end speaking

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/inmoov#50]

**Comment by moz4r** [comment]
worky for me.
But I added this to force things https://github.com/MyRobotLab/inmoov/commit/17b69b973b03b1bc229d49be0b6c93b126e0a02e

better ?

**Comment by hairygael** [comment]
Seems to work!
 I will test some more tomorrow

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-04-19 0:17 GMT+02:00 Anthony <notifications@github.com>:
