### ISSUE TITLE
Rename inmoovScript to inmoov

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/inmoov#51]

**Comment by moz4r** [comment]
Hi @kwatters ! about your question can we rename inmooscript to Inmoov without problem ? because there is already an inmoov folder at root ( used by jmonkey )

**Comment by Calamity01** [comment]
the inmoov folder hold the 3dmodel for the VinMoov. So it's all relate the
the InMoov stuff. It can probably be shared or if you think it's better, I
can move the vinMoov stuff elsewhere

**Comment by moz4r** [comment]
mix inmoov stuff is good idea ! I don't know how the folder from inmoov repo will be merged into the jar

**Comment by moz4r** [comment]
ok inmoovScript renamed to Inmoov and merge existing Inmoov folder while install

**Comment by moz4r** [comment]
kwatters: gestures directory should be renamed from "inmoovGestures" to just "gestures" ...
kwatters: (not sure why there's a subdirectory for COMPLETE_GESTURES ...
kwatters: all gestures should be in the same directory.

**Comment by moz4r** [comment]
InMoov as folder name

**Comment by moz4r** [comment]
we need to put somewhere minimal gestures, it is usefull for people using minimal inmoov. Minimal inmoov is no chatbot and few skeleton parts. I propose a new folder Minimal , inside we put basical globalised ear commands + minimal gesture.

**Comment by moz4r** [comment]
guys, whole project renamed. I hope I didnt broke anything. seem ok but not tested all. pushed virtual inmoov by default ( with right hand ) instead of fingerstarter inside configuration. Everyone ok ?
