### ISSUE TITLE
activate virtual inmoov + full inmoov

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/inmoov#54]

**Comment by hairygael** [comment]
Hello Anthony,
Great!
I just installed the latest develop branch to check.
VinMoov is activated along with InMoov, but it doesn't actuate when moveing
servo sliders or voice commande gestures.
Do you have it working simulteaneously?

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-04-19 17:05 GMT+02:00 Anthony <notifications@github.com>:

**Comment by hairygael** [comment]
Ah sorry I found what I did wrong. Forgot to copy a line in the checkupini.py

**Comment by moz4r** [comment]
I push mod at work work , just tested now, result is so cool !!!

**Comment by hairygael** [comment]
It's worky for you???
Arrgh

**Comment by hairygael** [comment]
Tested VinMoov with the French version and it works partially.
The arms are moving and working, but not the rothead, neckhead, jaw, hands and wrists.

**Comment by moz4r** [comment]
ok I will look forward on it, maybe an init delay problem I remember @Calamity01 spoke about something like this, maybe not related

**Comment by moz4r** [comment]
is it better now ?

**Comment by moz4r** [comment]
set full skeleton activated by default if scriptType=vinmoov

**Comment by hairygael** [comment]
My vinmoov is not moving anymore with version 2132.
I will need to investigate.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-05-02 0:42 GMT+02:00 Anthony <notifications@github.com>:

**Comment by moz4r** [comment]
Some good news here ?

**Comment by hairygael** [comment]
I didn't have the time to test with a more recent version of MRL...

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-05-10 11:38 GMT+02:00 Anthony <notifications@github.com>:

**Comment by Calamity01** [comment]
vinMoov is working fine with my own inMoov script with MRL 2161. So we should look in the inMoov repo script for the bug hunting

**Comment by hairygael** [comment]
I tested last night with 2156, and it works with the repo when selecting Virtual.
Though the right wrist is still not turning the correct direction.
I had a look to see what you suggested to modify that in the inmoov.java and also in the jml3.java.
But I do not want to brake something in there instead of fixing it.

**Comment by Calamity01** [comment]
add the following python line in the script after vinMoov is started

i01.vinMoovApp.setMinMaxAngles("RWrist",180,0)

that will set your min of the servo to = 180 degree in the vinMoov reference and max of the servo to = 0 degree in the vinMoov reference

I have refer to the method so you can find the proper names of the part

**Comment by hairygael** [comment]
Thanks Calamity,
Indeed that would fix for my personal instance, but all the beginners might think they didn't set their mappings correctly.
Should this line be modified:
maps.put("RWrist", new Mapper(0, 180, 0, 180));
to
maps.put("RWrist", new Mapper(0, 180, 180, 0));
https://github.com/MyRobotLab/myrobotlab/blob/develop/src/org/myrobotlab/jme3/InMoov3DApp.java

**Comment by Calamity01** [comment]
no, that line is just a linker so I could make your way of mapping servo to work with vinMoov. I eventually want to remove that line

Better work on how the joint is define
a few line before that line, you will see

rotationMask = ...   the value -1 or 1 define the orientation of the rotation (clockwise or counterclockwise)
angle = define the initial position of the part (rotation of the 3d model in his local world)

playing with those two value is better in the long term

**Comment by moz4r** [comment]
follow the friend post : https://github.com/MyRobotLab/myrobotlab/issues/71
