### ISSUE TITLE
Serial Neopixel

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/inmoov#59]
Time to test

**Comment by moz4r** [comment]
worky , @hairygael I saw you had problems about it.

**Comment by hairygael** [comment]
I will test it as soon as I can.
:)

**Comment by hairygael** [comment]
Neo pixel worky for me in USB. I haven't tried with RX/TX since version 1.0.2006

**Comment by moz4r** [comment]
I close this bug because no identified bug detected inside java or python land. We can repoen this bug later

**Comment by hairygael** [comment]
Ok

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-05-17 17:13 GMT+02:00 Anthony <notifications@github.com>:
