### ISSUE TITLE
rest() and fullspeed() broken

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/inmoov#63]
Hello Anthony,
Two of my main important gestures are broken and create an issue when called.
Rest() is not anymore within the folder COMPLETE_GESTURES. (if we need a gesture similar to rest() as a earAddCommand, I think it would be better to give it another name like "basic()" or "initial()". That way the rest() will stay within the COMPLETE_GESTURES folder. Also the speeds that were involved into that gesture are not there anymore. Because that gesture doesn't work, the robot doesn't start correctly set.

Fullspeed() is not worky anymore and doesn't take the eyes speed anymore, which was needed for to get a correct face tracking.

**Comment by moz4r** [comment]
Ok for strange reason function fullspeed() was called ( lowercase )
So I create an other function, to call the good function fullSpeed ( to not break an other thing )

def fullspeed():
  fullSpeed()
