### ISSUE TITLE
mapping issue leftArm.omoplate

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/inmoov#65]
I have a mapping issue regarding leftArm.omoplate. Although it is correctly mapped, same as the right arm, the mapping is not active.

**Comment by moz4r** [comment]
tested to increase value with my cobaye, left omoplate dislocate good :)
When you say not active, omoplate physical range still 0>180 ?

those are my values

[SERVO_MINIMUM_MAP_OUTPUT]
omoplate = 10

[SERVO_MAXIMUM_MAP_OUTPUT]
omoplate = 90

[MINIMUM_MAP_INPUT]
omoplate = 0

[MAXIMUM_MAP_INPUT]
omoplate = 180

**Comment by hairygael** [comment]
These are my values for the leftArm, I have almost similar values for the rightArm and it works fine.

[SERVO_MINIMUM_MAP_OUTPUT]
omoplate=42

[SERVO_MAXIMUM_MAP_OUTPUT]
omoplate = 80

[MINIMUM_MAP_INPUT]
omoplate = 0

[MAXIMUM_MAP_INPUT]
omoplate = 180

So the armLeft omoplate when doing Da Vinci only moves about half way up and stops. What is odd, is the slider. if I go to 80 which should be the end stop, now I can go more and the arm could dismantle and go much too far.

**Comment by moz4r** [comment]
can you check with servo_calibration ,left omoplate range values ?

**Comment by hairygael** [comment]
Both arms have the same config values and you can see the difference given in the sliders:
![image](https://cloud.githubusercontent.com/assets/8484551/25726525/eeeb3b9c-3124-11e7-9aff-8a6134e74832.png)
![image](https://cloud.githubusercontent.com/assets/8484551/25726572/147f0942-3125-11e7-9955-d1523e5d1cae.png)

**Comment by moz4r** [comment]
I hope there is a difference ( or it is black magic ! )
maybe there is a difference between leftarm and rightarm about omoplate inside 
[MINIMUM_MAP_INPUT]
[MAXIMUM_MAP_INPUT]
We can see in your screenshot values are not the same.
I have reproduced too a similar issue :  

![image](https://cloud.githubusercontent.com/assets/18124594/25727119/cf845682-3127-11e7-9fa5-bc14a19c672b.png)

other possible issue : some error in config file, so config not parsed
No subconcious voice error at startup about bad config file ?

can you post your skeleton config ? So I can look at it more further

**Comment by hairygael** [comment]
Gee, I found the issue!
Thanks for overlooking! Some update as modified my config 
[MINIMUM_MAP_INPUT]
[MAXIMUM_MAP_INPUT]
The left was set to 0-->180 instead of 10-->80
Looking in a older folder my values were okay, so I don't know what happened.
Anyway its all good now.

**Comment by moz4r** [comment]
great ! no more dislocated skeleton it hurt too much. 
I understand you use input to set your limits, so your map is map(10,80,0,180) instead of classical map(0,180,10,80) . but if worky don't touch nothing ! other post other day i m not an expert about angle standardisation

**Comment by hairygael** [comment]
My map should be map(10,80,42,80) for leftArm.omoplate. But on the full script I have leftArm.omoplate.map(0,180,42,80)
Me neither, there is things I do not understand...

**Comment by hairygael** [comment]
By the way, does the jaw works okay for you?

**Comment by moz4r** [comment]
this is my mouthcontrol freshly tested to compare

https://www.youtube.com/edit?o=U&video_id=wBaLPyU2xJQ
