### ISSUE TITLE
Tweak vinmoov to use it as fullscreen monitor

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/inmoov#69]
maybe before or after manticore

**Comment by moz4r** [comment]
started some work about it. just a test to display some informations like batterie / arduino / micro ... Inside vinmoov main screen

**Comment by moz4r** [comment]
![image](https://cloud.githubusercontent.com/assets/18124594/25686089/0d2bfca4-306c-11e7-95c5-2b2b89bb0ed1.png)

**Comment by supertick** [comment]
Ahahaha 😂  looks like an album cover ...
Booyah!

**Comment by hairygael** [comment]
Hey nice!

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-05-04 2:14 GMT+02:00 GroG <notifications@github.com>:

**Comment by supertick** [comment]
closed or is there more to do ?

**Comment by moz4r** [comment]
some little work to do 
- finish battery indicator
- adruinos status
- services status
