### ISSUE TITLE
jm3 directory not loaded

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/inmoov#72]
Using MRL 1.0.1156, the jm3 directory isn't present inside the InMoov directory, is it normal?

**Comment by moz4r** [comment]
No :) 
Sometime when I update the repo script ( because what is Inside the jar toooo old ) I delete by mistake the jm3 folder. Maybe you do same mistake ?
tested Inside 2163 jm3 is here when Inmoov service installed

**Comment by hairygael** [comment]
I will need to see with the latest build to see if it's in it.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-05-12 14:31 GMT+02:00 Anthony <notifications@github.com>:

**Comment by moz4r** [comment]
can we close it ?

**Comment by hairygael** [comment]
Just checked with latest build 2173.
Directory is loaded with " install all". I didn't test to see if install
inmoov only loda the folder though.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-05-17 16:54 GMT+02:00 Anthony <notifications@github.com>:

**Comment by moz4r** [comment]
great 1 less bug !
