### ISSUE TITLE
OpenWeather conflict

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/inmoov#80]
Hello weather man!
English aiml set used to work very nice for weather.
We could ask any city weather in celsius or in farenheit and it would give various answers related with the actual weather of the desired location. It was handy for demonstrations when I was in other countries..
Now with English version, it just says some of the </li/> options without giving the weather.
:(

**Comment by moz4r** [comment]
mmm conflic with sraix, you have 2 options
- delete openweathermap english chatbot entries related, or rename it
- using openweathermap mrl service by setting the api key >service_H_OpenWeatherMap.config
You can get a free key here : https://home.openweathermap.org/api_keys

![le-journal-des-medias-du-11-decembre-tf1-permet-a-ses-telespectateurs-d-etre-presentateur-meteo_news_full-1](https://cloud.githubusercontent.com/assets/18124594/26607592/8e043e5a-4597-11e7-829c-fcfbfbddda17.jpg)

**Comment by hairygael** [comment]
Okay, I just tried to remove weathermap in _inmoovChatbot and the conflict is gone.
I will rename the weather map srai to something different to keep the option.

**Comment by hairygael** [comment]
Modified the word "weather" to "forecast". Conflict is gone and both can be used.
