### ISSUE TITLE
jaw not moving in Russian

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/inmoov#81]
Certainly an issue related to the alphabet.

**Comment by Calamity01** [comment]
yes certainly... mouthcontrol is looking for voyels (a,e,i...) to form some
kind of even to open/close the mouth. If those voyels are not present, it
don't know what to do and don't open the mouth

Le mar. 30 mai 2017 à 20:48, Langevin Gael <notifications@github.com> a
écrit :

**Comment by moz4r** [comment]
ohh I was thinking I had hardware problem ! pushed some russian vowels and french accent too

**Comment by hairygael** [comment]
Thanks Calamity for the info!
@Anthony is it working now with what you pushed?

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-05-31 15:43 GMT+02:00 Anthony <notifications@github.com>:

**Comment by moz4r** [comment]
yes it is worky now

**Comment by hairygael** [comment]
Thanks for the response.
I'm getting InMoov ready for Madrid, Russian is not what I need now, ehehe!
I will check if it works in Russian anyway and let you know.

**Comment by moz4r** [comment]
The day you go inside international space station, please let me know !

**Comment by hairygael** [comment]
Tested with version 1.0.2226 and latest inmoov-develop. Mouth is moving once all launching is done. That's very good.
Gee, VoiceRSS is very slow to fetch the mp3. But once cached it's okay.
