### ISSUE TITLE
OpenCV with face tracking is an issue

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/inmoov#83]
Filters do appear, PyramidDown, Gray, FaceDetect, but it stays without effecting the capture.
Do you have the same?

**Comment by hairygael** [comment]
I'm wondering if OpenCV is fixed and if it's an issue on my side.

**Comment by moz4r** [comment]
![image](https://cloud.githubusercontent.com/assets/18124594/26748312/dad0abb2-47fc-11e7-8eee-b23baa64146c.png)

Someone here have a master's degree in tracking ? 

I will test this soon,
I think the goal is : tracking worky from inmoov service based on servo mappings.

**Comment by moz4r** [comment]
wip , other tickets opened
