### ISSUE TITLE
Is this deprecated?

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/inmoov#85]
global RobotCanMoveHeadWhileSpeaking
   RobotCanMoveHeadWhileSpeaking=0

And replaced by:
i01.disableRobotCanMoveHeadRandom(15)

If yes, there is gestures that need to be checked out.

**Comment by moz4r** [comment]
Yes deprecated, because pushed Inside Inmoov service ( gestures already checked )

**Comment by hairygael** [comment]
ok thanks
