### ISSUE TITLE
Русский язык

### ISSUE THREAD

**Issue by AlexInMoov** [MyRobotLab/inmoov#98]
Приветствую Вас. Вот файлы "aiml" исправленные для русского языка: https://yadi.sk/d/0s7GD9gN3LxKgg
вот файлы "Жесты" для поддержки разных языков: https://yadi.sk/d/FhFskLnW3LxSbd
но в них нужно исправить файлы: https : //yadi.sk/d/1a3a5Prw3LxQAT
вот файлы "InMoov \ system \ languagePack \ ru" исправленные для русского языка: https://yadi.sk/d/UpRB8kwG3LxGFP
спасибо за сотрудничество.

**Comment by moz4r** [comment]
https://github.com/MyRobotLab/inmoov/issues/90
